---
# Trigger restart only when Splunk is currently running; add add'l when clauses during include_tasks invocation as needed
- name: "Get Splunk status"
  command: "{{ splunk.exec }} status --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
  register: splunk_status
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Trigger restart
  command: ls
  changed_when: splunk_status.rc == 0
  notify:
    - Restart the splunkd service
